
package com.anil.indiamart.resource;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductCatelogImpl", targetNamespace = "http://resource.indiamart.anil.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductCatelogImpl {


    /**
     * 
     * @return
     *     returns com.anil.indiamart.resource.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct", targetNamespace = "http://resource.indiamart.anil.com/", className = "com.anil.indiamart.resource.GetProduct")
    @ResponseWrapper(localName = "getProductResponse", targetNamespace = "http://resource.indiamart.anil.com/", className = "com.anil.indiamart.resource.GetProductResponse")
    @Action(input = "http://resource.indiamart.anil.com/ProductCatelogImpl/getProductRequest", output = "http://resource.indiamart.anil.com/ProductCatelogImpl/getProductResponse")
    public Product getProduct();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductDetails", targetNamespace = "http://resource.indiamart.anil.com/", className = "com.anil.indiamart.resource.GetProductDetails")
    @ResponseWrapper(localName = "getProductDetailsResponse", targetNamespace = "http://resource.indiamart.anil.com/", className = "com.anil.indiamart.resource.GetProductDetailsResponse")
    @Action(input = "http://resource.indiamart.anil.com/ProductCatelogImpl/getProductDetailsRequest", output = "http://resource.indiamart.anil.com/ProductCatelogImpl/getProductDetailsResponse")
    public List<String> getProductDetails();

}
